services:
  backend:
    build: backend
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=duykhanhhotel
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - spring-postgres
      - react-spring
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=duykhanhhotel
      - POSTGRES_PASSWORD=1234
    expose:
      - 5432
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    networks:
      - react-spring
    environment:
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - backend
    expose:
      - 3306
      - 33060
    
volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db/data
networks:
  spring-postgres:
  react-spring:
