server:
  servlet:
    context-path: /api
#spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect

spring:
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
#    url: jdbc:postgresql://localhost:5432/duykhanhhotel
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties: 
      hibernate:  
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

springdoc:
  paths-to-match: /items/**, /item-types/**, /room-types/**, /house-types/**, /room-prices/**, /room-configs/**, /rooms/**, /**/customers/**, /**/purchased-items/**